// <auto-generated />
namespace Vic.SportsStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProductR2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductR2));
        
        string IMigrationMetadata.Id
        {
            get { return "201911021930578_ProductR2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
